name: Test Deployment

on:
  pull_request:
    branches: [website]

jobs:
  test-deploy:
    name: Test Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - name: Test build
        working-directory: ./
        run: |
          npm ci
          npm run build